### ISSUE TITLE
Invariant Violation: Calling synchronous methods on native modules is not supported in Chrome.

### ISSUE THREAD

**Issue by niall-shaw** [jpudysz/react-native-is-maestro#13]
App will crash if using chrome debugger and `isMaestro` is present

**Comment by jpudysz** [comment]
Thanks for the report @niall-shaw . I will take a look. Can you give more details?
Do you use expo?

**Comment by niall-shaw** [comment]
Hey @jpudysz ,

No, we don't use expo. 
We are using react-native version `0.71.11`, and this problem is happening on both Android and iOS.
Only happens when using debugger, and if a call to `isMaestro` is made

**Comment by jpudysz** [comment]
Thanks for the clarification, I will try to fix it today 🙏

**Comment by jpudysz** [comment]
Do you use new arch enabled or not?

**Comment by niall-shaw** [comment]
@jpudysz , sorry for the delayed response.
We do not have new arch enabled yet, and also we don't have Hermes enabled.

Thanks.

**Comment by niall-shaw** [comment]
Reading up on the new architecture vs old architecture, and JSI.
It seems it may still not be possible for asynchronous native calls using the old architecture, so perhaps the PR I created may be necessary only for old architecture:

> (The Bridge) was asynchronous: one layer submitted the data to the bridge and asynchronously "waited" for the other layer to process them, even when this was not really necessary.

**Comment by niall-shaw** [comment]
@jpudysz , perhaps you can also expose an asynchronous implementation (such as the PR I created), for configurations when necessary?

**Comment by jpudysz** [comment]
@niall-shaw I'm coming back from vacation on Friday. I will try to disable the hermes and try one more time

**Comment by jpudysz** [comment]
Hello @niall-shaw, sorry for the additional days of waiting. I have reproduced your issue and was able to potentially fix it.

Can you verify it by modifying `node_modules/react-native-is-maestro/src/index.tsx`:

```ts
const isDebuggingWithChrome = () => !global.nativeCallSyncHook

export const isMaestro = (): boolean => {
    if (isDebuggingWithChrome()) {
        return false
    }

    return MaestroModule.isMaestro()
}
```

If that works for you, I will release a patch.

By the way, keep in mind that from RN 0.73, the Chrome Debugger Tools will be deprecated:  https://reactnative.dev/docs/next/debugging#chrome-developer-tools
