### ISSUE TITLE
Executing maestro test command doesn't detect maestro

### ISSUE THREAD

**Issue by amanjeetsingh150** [jpudysz/react-native-is-maestro#3]
When I execute simple flow like:

```
appId: org.reactjs.native.example.IsMaestroExample
---
- launchApp
```

and execute with `maestro test ./flow.yaml`, it doesn't seem to detect maestro. Although when tests execute from maestro record command the sample app detects maestro.

I think what ends up happening is that this flow is very short and the socket actually closes before we detect maestro is running. To confirm this I ran a slightly longer flow with additional tapOn command and bam it got detected:

```
appId: org.reactjs.native.example.IsMaestroExample
---
- launchApp
- tapOn: "Some sample tap"
```

Recording for issue:

https://user-images.githubusercontent.com/12881364/217201440-32d42485-4167-40da-91cb-7a5bf8398936.mov

PS: We will soon be working on a solution that can help detect maestro for both android and iOS for all platforms. But this repo is definitely useful for all react native users. Thanks again for the contribution 🙌

**Comment by jpudysz** [comment]
@amanjeetsingh150 thank you for the report. I think it's fixable. I'm checking if maestro is running while the view has been mounted on React Native side. I can also do it from Obj-C side, and it will be available before view mounts. I will try to repro it and push a fix.

**Comment by jpudysz** [comment]
@amanjeetsingh150 unfortunately, this feature won't be supported.
React Native is launching too late, and there is no way to detect maestro in a split second.
Also, I can't see any benefits in supporting it from Obj-C as it won't match the real-world use case scenario.
