### ISSUE TITLE
Library is detecting a different iOS port to what's recommended

### ISSUE THREAD

**Issue by matt-dalton** [jpudysz/react-native-is-maestro#7]
Thanks for implementing this library. I'm sure there's a good reason for this, but how come the library is [detecting different ports](https://github.com/jpudysz/react-native-is-maestro/blob/7d0407c76d9d6a166fe8a3a0930a598de61f4c67/ios/IsMaestro.mm#L67) to the ones [Maestro recommends](https://maestro.mobile.dev/advanced/detect-maestro-in-your-app). Should these be changed?

**Comment by jpudysz** [comment]
Hello, @matt-dalton I think that documentation is outdated. This port was available around CLI version 1.19.
Based on the slack discussion from CLI v. 1.23 we should access different port. Android stays the same.
